# Anzahl der Minecraft-Server-Instanzen
# Setzen Sie auf 0, um den Server auszuschalten
# Setzen Sie auf 1, um den Server einzuschalten
replicaCount: 1

# Rest wie vorher...
resources:
  limits:
    memory: "6Gi"
    cpu: "3000m"
  requests:
    memory: "4Gi"
    cpu: "2000m"

# Speicherkonfiguration
storage:
  world: 5Gi
  cash: 3Gi

# Init Chart Ressourcen
initResources:
  releaseName: "init"
  minecraftVersion: "1.21.5"

# Server-Konfiguration
server:
  java:
    maxMemory: "4G"
    minMemory: "2G"
  properties:
    allowFlight: "false"
    allowNether: "true"
    difficulty: "easy"
    enableCommandBlock: "false"
    gamemode: "survival"
    levelName: "world"
    maxPlayers: "20"
    motd: "Ein Minecraft Server mit Kubernetes"
    onlineMode: "true"
    pvp: "true"
    viewDistance: "10"

# RCON-Konfiguration
rcon:
  enabled: true
  password: "MeinSicheresRCONPasswort" 
  port: 25575

# Service-Konfiguration
service:
  nodePort: 30565
  rconNodePort: 30575