resources:
  limits:
    memory: "6Gi"
    cpu: "3000m"
  requests:
    memory: "4Gi"
    cpu: "2000m"

# Speicherkonfiguration
storage:
  world: 5Gi
  cash: 3Gi

# Init Chart Ressourcen
initResources:
  # Name des Init-Release, von dem die Ressourcen verwendet werden
  releaseName: "init"
  # Minecraft Version mit Bindestrichen statt Punkten
  minecraftVersion: "1-21-5"

# Server-Konfiguration
server:
  # Zeit in Sekunden, die der Pod laufen soll
  runTime: 86400
  properties:
    allowFlight: "false"
    allowNether: "true"
    difficulty: "easy"
    enableCommandBlock: "false"
    gamemode: "survival"
    levelName: "world"
    maxPlayers: "20"
    motd: "Ein Minecraft Server mit Kubernetes"
    onlineMode: "true"
    pvp: "true"
    viewDistance: "10"
