apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-server-properties
data:
  server.properties: |
    #Minecraft server properties
    #Die Servereinstellungen für Ihren Minecraft-Server
    allow-flight={{ .Values.server.properties.allowFlight }}
    allow-nether={{ .Values.server.properties.allowNether }}
    broadcast-console-to-ops=true
    difficulty={{ .Values.server.properties.difficulty }}
    enable-command-block={{ .Values.server.properties.enableCommandBlock }}
    enable-jmx-monitoring=false
    enable-query=false
    enable-rcon=true
    rcon.password={{ .Values.rcon.password | default "" }}
    rcon.port={{ .Values.rcon.port | default "25575" }}
    enable-status=true
    enforce-whitelist=false
    entity-broadcast-range-percentage=100
    force-gamemode=false
    function-permission-level=2
    gamemode={{ .Values.server.properties.gamemode }}
    generate-structures=true
    generator-settings=
    hardcore=false
    level-name={{ .Values.server.properties.levelName }}
    level-seed=
    level-type=default
    max-build-height=256
    max-players={{ .Values.server.properties.maxPlayers }}
    max-tick-time=60000
    max-world-size=29999984
    motd={{ .Values.server.properties.motd }}
    network-compression-threshold=-1
    online-mode={{ .Values.server.properties.onlineMode }}
    op-permission-level=4
    player-idle-timeout=0
    prevent-proxy-connections=false
    pvp={{ .Values.server.properties.pvp }}
    query.port=25565
    rate-limit=0
    resource-pack=
    resource-pack-sha1=
    server-ip=0.0.0.0
    bungeecord=true
    server-port=25565
    snooper-enabled=true
    spawn-animals=true
    spawn-monsters=true
    spawn-npcs=true
    spawn-protection=16
    sync-chunk-writes=true
    use-native-transport=true
    view-distance={{ .Values.server.properties.viewDistance }}
    white-list=false