apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
    name: minecraft
    nodePort: {{ .Values.service.nodePort | default 30565 }}
  selector:
    app: {{ .Release.Name }}