apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-world-sync
data:
  world-sync.sh: |
    #!/bin/bash
    # Skript zum Synchronisieren der Weltdaten zwischen Servern
    
    WORLD_NAME=$(grep "level-name=" /config/server.properties | cut -d'=' -f2)
    echo "Synchronisiere Weltdaten für $WORLD_NAME von Quelle zu Ziel..."
    
    if [ "$1" == "to-backup" ]; then
      # Kopieren von dieser Welt zum Backup
      echo "Kopiere von dieser Welt zu Backup-Welt..."
      mkdir -p /backup-world/$WORLD_NAME
      cp -rf /minecraft-world/$WORLD_NAME/* /backup-world/$WORLD_NAME/
    elif [ "$1" == "from-backup" ]; then
      # Kopieren vom Backup zu dieser Welt
      echo "Kopiere von Backup-Welt zu dieser Welt..."
      mkdir -p /minecraft-world/$WORLD_NAME
      cp -rf /backup-world/$WORLD_NAME/* /minecraft-world/$WORLD_NAME/
    else
      echo "Ungültiger Parameter: $1"
      exit 1
    fi
    
    echo "Synchronisation abgeschlossen!"