apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.yml: |
    server_connect_timeout: 5000
    listeners:
    - query_port: 25565
      motd: '&1Minecraft Server mit Zero-Downtime Updates'
      tab_list: GLOBAL_PING
      query_enabled: false
      proxy_protocol: false
      ping_passthrough: false
      priorities:
      - server1
      bind_local_address: true
      host: 0.0.0.0:25565
      max_players: 20
      tab_size: 60
      force_default_server: false
    remote_ping_cache: -1
    network_compression_threshold: 256
    permissions:
      admin:
      - bungeecord.command.alert
      - bungeecord.command.end
      - bungeecord.command.ip
      - bungeecord.command.reload
      default:
      - bungeecord.command.server
      - bungeecord.command.list
    log_pings: true
    connection_throttle_limit: 3
    timeout: 30000
    player_limit: -1
    prevent_proxy_connections: false
    ip_forward: true
    groups:
      admin:
      - admin
    connection_throttle: 4000
    online_mode: true
    forge_support: true
    servers:
      {{- range .Values.servers }}
      {{ .name }}:
        motd: 'Minecraft Server {{ .name }}'
        address: {{ .address }}:{{ .port }}
        restricted: false
      {{- end }}
    {{- if .Values.servers }}
    priorities:
    {{- range .Values.servers }}
    {{- if .isDefault }}
    - {{ .name }}
    {{- end }}
    {{- end }}
    {{- end }}