# Proxy-Konfiguration
proxy:
  type: "WATERFALL"  # Alternative BungeeCord implementation
  image: "itzg/bungeecord:latest"
  port: 25565
  
# Minecraft-Server-Konfiguration
servers:
  - name: "server1"
    address: "minecraft-server-headless" # Einfacher Service-Name
    port: 25565
    isDefault: true
  - name: "server2"
    address: "minecraft-server-headless" # Einfacher Service-Name
    port: 25565
    isDefault: false

# Ressourcen-Beschränkungen
resources:
  limits:
    cpu: "1000m"
    memory: "1G"
  requests:
    cpu: "500m"
    memory: "1G"

# Service-Konfiguration
service:
  type: NodePort
  nodePort: 30566 # Gleicher Port wie Ihr aktueller Minecraft-Server

rcon:
  enabled: true
  password: "MeinSicheresRCONPasswort"
  port: 25575