# Proxy-Konfiguration
proxy:
  type: "WATERFALL"  # Alternative BungeeCord implementation
  image: "itzg/bungeecord:latest"
  port: 25565
  
# Minecraft-Server-Konfiguration
servers:
  - name: "minecraft"
    address: "minecraft-server-service"  # Ändere dies von "minecraft-server-headless"
    port: 25565
    isDefault: true

# Ressourcen-Beschränkungen
resources:
  limits:
    cpu: "1000m"
    memory: "1G"
  requests:
    cpu: "500m"
    memory: "1G"

# Service-Konfiguration
service:
  type: NodePort
  nodePort: 30566 # Port für Spieler-Verbindungen

rcon:
  enabled: true
  password: "MeinSicheresRCONPasswort"
  port: 25575