apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  labels:
    app: minecraft
spec:
  type: NodePort
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
    nodePort: 30565  # Dies kann weggelassen werden, dann wählt Kubernetes einen zufälligen Port zwischen 30000-32767
  selector:
    app: minecraft  # Dieses Label muss mit dem Label Ihres Pods übereinstimmen
